### ISSUE TITLE
Get error while running autodraw(shapes).then(results => {})

### ISSUE THREAD

**Issue by manizand** [mathieudutour/autodraw#1]
```
> autodraw(shapes).then(results => {})
Promise {
  <pending>,
  domain: 
   Domain {
     domain: null,
     _events: { error: [Function: debugDomainError] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] } }
> 
```
{ autodraw: '0.1.0',
  npm: '5.5.1',
  ares: '1.10.1-DEV',
  cldr: '31.0.1',
  http_parser: '2.7.0',
  icu: '59.1',
  modules: '57',
  nghttp2: '1.25.0',
  node: '8.9.1',
  openssl: '1.0.2m',
  tz: '2017b',
  unicode: '9.0',
  uv: '1.15.0',
  v8: '6.1.534.47',
  zlib: '1.2.11' }

**Comment by manizand** [comment]
@mathieudutour

**Comment by mathieudutour** [comment]
what is the error?

**Comment by manizand** [comment]
I mean unexpected results:
```
Promise {
  <pending>,
  domain: 
   Domain {
     domain: null,
     _events: { error: [Function: debugDomainError] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] } }
```

**Comment by mathieudutour** [comment]
hum that's not unexpected, you are just logging the promise instead of the result. You might want to check what promises are: https://developers.google.com/web/fundamentals/primers/promises
